CREATE TABLE event (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	title varchar(20) NOT NULL,
	description varchar(5000),
    category varchar(10) NOT NULL,
    location varchar(30) NOT NULL,
    event_date DATETIME NOT NULL,
    creation_date DATETIME NOT NULL,
    capacity int NOT NULL,
    num_participants int NOT NULL,
	PRIMARY KEY (id)
);